//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicateOracleDBIntoMSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public decimal ID { get; set; }
        public decimal QUANTITY { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public decimal DISCOUNT { get; set; }
        public Nullable<decimal> CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
