CREATE TABLE PRODUCTS 
(
  ID INT NOT NULL 
, NAME NVARCHAR2(100) NOT NULL 
, PRICE DECIMAL NOT NULL 
, SUPPLIER_ID INT NOT NULL 
, CATEGORY_ID INT NOT NULL 
, MEASURE_ID INT NOT NULL 
, CONSTRAINT PRODUCTS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN PRODUCTS.ID IS 'Primary key';

COMMENT ON COLUMN PRODUCTS.SUPPLIER_ID IS 'Foreign key to the suppliers table.';

COMMENT ON COLUMN PRODUCTS.CATEGORY_ID IS 'Foreign key to the categories table.';

COMMENT ON COLUMN PRODUCTS.MEASURE_ID IS 'Foreign key to the categories table.';

CREATE SEQUENCE PRODUCTS_SEQ;

CREATE TRIGGER PRODUCTS_TRG 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRODUCTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/