CREATE TABLE MEASURES 
(
  ID INT NOT NULL 
, NAME NVARCHAR2(50) NOT NULL 
, CONSTRAINT MEASURES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN MEASURES.ID IS 'Primary key.';

CREATE SEQUENCE MEASURES_SEQ;

CREATE TRIGGER MEASURES_TRG 
BEFORE INSERT ON MEASURES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MEASURES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/