CREATE TABLE CUSTOMERS 
(
  ID INT NOT NULL 
, CUSTOMER_NAME NVARCHAR2(100) NOT NULL 
, ADDRESS NVARCHAR2(100) NOT NULL 
, PHONE NVARCHAR2(20) NOT NULL 
, CONSTRAINT CUSTOMERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN CUSTOMERS.ID IS 'Primary key.';

CREATE SEQUENCE CUSTOMERS_SEQ;

CREATE TRIGGER CUSTOMERS_TRG 
BEFORE INSERT ON CUSTOMERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CUSTOMERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/