CREATE TABLE SUPPLIERS 
(
  ID INT NOT NULL 
, SUPPLIER_NAME NVARCHAR2(100) NOT NULL 
, ADDRESS NVARCHAR2(100) NOT NULL 
, PHONE NVARCHAR2(20) NOT NULL 
, CONSTRAINT SUPPLIERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN SUPPLIERS.ID IS 'Primary key';

CREATE SEQUENCE SUPPLIERS_SEQ;

CREATE TRIGGER SUPPLIERS_TRG 
BEFORE INSERT ON SUPPLIERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SUPPLIERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/