-- USER SQL
CREATE USER SUPERMARKET IDENTIFIED BY supermarket 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER SUPERMARKET QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO SUPERMARKET ;
GRANT "RESOURCE" TO SUPERMARKET ;

-- SYSTEM PRIVILEGES