//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsSQLContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int SupplierId { get; set; }
        public int CategoryId { get; set; }
        public int MeasureId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Measure Measure { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
